import { i18n } from "@/i18n-config"

import { getLocale } from "../../locales"
import "../globals.css"

export const metadata = {
  title: "Themesei - Upgrade WordPress with modern technologies, like Next.js",
  description: "Generated by create next app",
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode
  params: { lang: string }
}) {
  return (
    <html lang={lang}>
      <body>{children}</body>
    </html>
  )
}
